// src/pages/Businesses/Businesses.tsx
import { A, useRouteData } from "@solidjs/router";
import {Avatar, Box, Chip, Container, List, ListItemAvatar, ListItemButton, ListItemText, Paper, Stack} from "@suid/material";
import {createResource, For} from "solid-js";
import Header from "../../components/Header";
import Searchbox from "../../components/Searchbox";
import {sanityClient, urlFor} from "../../lib/sanity";
import { businessTypes } from "../../lib/businessTypes";
import { Business } from "../../types/SanitySchema";


export default function Businesses() {
	const data = useRouteData<typeof BusinessesGetData>();

	return (
		<>
			<Header 
				title="Afaceri locale"
				back
			/>
			<Container>
				<Stack>
					<Searchbox/>
					
					<Box
						sx={{
							display: "flex",
							gap: 1,
							flexDirection: "row",
							overflowX: "auto",
						}}
					>
						<For each={Array.from(businessTypes, ([_, value]) => value)}>
							{(businessType) => (
								<Chip
									label={businessType.name}
									icon={<businessType.icon/>}
									variant="outlined"
									color="secondary"
								/>
							)}
						</For>
					</Box>


					<Paper>
						<List>
							<For each={data()}>
								{(business) => (
									<A href={`/businesses/${business.slug?.current}`}>
										<ListItemButton>
											<ListItemAvatar>
												<Avatar 
													src={urlFor(business.logo).width(64).height(64).url()}
													variant="rounded"
												/>
											</ListItemAvatar>
											<ListItemText 
												primary={business.name} 
												secondary={business.description} 
												secondaryTypographyProps={{ noWrap: true }}
											/>
										</ListItemButton>
									</A>
								)}
							</For>
						</List>
					</Paper>
				</Stack>
			</Container>
		</>
	);
}


const fetcher = async () => {
	const res = await sanityClient.fetch(`*[_type == "business"] { slug, name, description, logo, isSponsor } | order(isSponsor desc)`)
		.catch(() => null);

	return res;
}

export function BusinessesGetData() {
	const [data] = createResource<Business[]>(fetcher);

	return data;
}

// src/routes/businesses/+page.svelte
<script lang="ts">
	import { businessTypes } from "$lib/businessTypes";
	import { urlFor } from "$lib/sanity";
	import { flip } from "svelte/animate";
	import Badge from "../../components/Badge.svelte";
	import Container from "../../components/Container.svelte";
	import Header from "../../components/Header.svelte";
	import Stack from "../../components/Stack.svelte";
	import ListItem from "../../components/ListItem.svelte";
	import type { PageData } from "./$types";
	import { queryParam, ssp } from "sveltekit-search-params";

	export let data: PageData;

	$: ({ businesses } = data);

	const filter = queryParam("filter", ssp.string(), {
		pushHistory: false
	});

	let scrollContainer: HTMLDivElement;
	function setFilter(value: string[]) {
		$filter = value.join(",");

		scrollContainer.scrollTo({ left: 0, behavior: "smooth" });
	}

	// Sort by first in filter
	$: businessTypesSorted = [...businessTypes].sort((a, b) => {
		const aIndex = $filter?.split(",").indexOf(a[0]) ?? -1;
		const bIndex = $filter?.split(",").indexOf(b[0]) ?? -1;

		return bIndex - aIndex;
	});
</script>

<Header back title="Afaceri" />

<Container>
	<Stack>
		<div
			class="flex flex-row overflow-scroll gap-2"
			bind:this={scrollContainer}
		>
			{#each businessTypesSorted as [key, value] (key)}
				<div
					animate:flip={{ duration: 200 }}
				>
					<Badge
						icon={value.icon}
						outline={!$filter?.split(",").includes(key)}
						color="secondary"
						class="badge-lg"
						on:click={() => {
							const filters = $filter?.split(",") ?? [];

							if (filters.includes(key)) {
								setFilter(filters.filter((f) => f !== key));
							} else {
								setFilter([...filters, key]);
							}
						}}
					>
						{value.name}
					</Badge>
				</div>
			{/each}
		</div>

		<div class="bg-neutral text-neutral-content p-2 rounded">
			{#each businesses as business}
				<a href="/businesses/{business.slug?.current}">
					<ListItem
						button
						primary={business.name}
						secondary={business.description}
						img={urlFor(business.logo).width(64).height(64).url()}
					/>
				</a>
			{/each}
		</div>
	</Stack>
</Container>
