// app/src/routes/news/archive/+page.svelte
<script lang="ts">
	import Container from "$lib/components/Container.svelte";
	import Header from "$lib/components/Header.svelte";
	import ListItem from "$lib/components/ListItem.svelte";
	import Stack from "$lib/components/Stack.svelte";
	import { urlFor } from "$lib/utils/sanity";
	import type { PageData } from "./$types";

	export let data: PageData;
</script>

<Header back title="Arhiva" />

<Container>
	<Stack>
		{#each data.articles as article}
			<a href="/news/{article.slug?.current}">
				<ListItem
					button
					primary={article.title}
					img={urlFor(article.cover).width(64).height(64).url()}
					secondary="#{article.tags?.join(' #')} &middot; {new Date(
						article._createdAt,
					).toLocaleDateString('ro')}"
				/>
			</a>
		{/each}
	</Stack>
</Container>

// src/pages/News/Archive.tsx
import {A, useRouteData} from "@solidjs/router"
import {Alert, Container, List, ListItem, ListItemButton, ListItemText} from "@suid/material";
import {createResource, For, Show} from "solid-js"
import Header from "../../components/Header"
import {sanityClient} from "../../lib/sanity"
import {Article} from "../../types/SanitySchema";


export default function Archive() {
	const data = useRouteData<typeof ArchiveGetData>();

	return (
		<>
			<Header
				title="Arhiva"
				back
			/>
			<Container>
				<List>
					<Show when={data()?.length === 0}>
						<Alert severity="info">
							Nu avem stiri inca.
						</Alert>
					</Show>
					<Show when={data() === undefined}>
						<Alert severity="info">
							Se incarca...
						</Alert>
					</Show>
					<Show when={data() === null}>
						<Alert severity="error">
							A aparut o eroare
						</Alert>
					</Show>
					<For each={data()}>
						{article => (
							<ListItemButton component={A} href={`/news/${article.slug?.current}`}>
								<ListItemText
									primary={article.title}
									secondary={new Date(article._createdAt).toLocaleDateString("ro")}
								/>
							</ListItemButton>
						)}
					</For>
				</List>
			</Container>
		</>
	)
}


const fetcher = async () => {
	const data = await sanityClient.fetch<Article[]>(`*[_type == "article"] | order(_createdAt desc)`)

	return data;
}

export function ArchiveGetData() {
	const [data] = createResource(fetcher);

	return data;
}
