// src/components/ContactList.tsx
import {List, ListItemButton, ListItemIcon, ListItemText, ListSubheader, SvgIcon} from "@suid/material";
import {Show} from "solid-js";

import EmailIcon from "@suid/icons-material/Email";
import PhoneIcon from "@suid/icons-material/Phone";
import FacebookSvg from "../resources/icons/facebook.svg?component-solid";
import InstagramSvg from "../resources/icons/instagram.svg?component-solid";
import WebsiteIcon from "@suid/icons-material/Web";

interface ContactList {
	website?: string,
	phone?: string,
	email?: string,
	facebook?: string,
	instagram?: string,
}


export default function ContactList(props: ContactList) {

	return (
		<List>
			<ListSubheader disableSticky>
				Contact
			</ListSubheader>
			<Show when={props?.website}>
				<ListItemButton 
					component="a"
					href={props.website} 
					target="_blank"
				>
					<ListItemIcon>
						<WebsiteIcon />
					</ListItemIcon>
					<ListItemText 
						primary="Website"
						secondary={props.website}
					/>
				</ListItemButton>
			</Show>
			<Show when={props?.email}>
				<ListItemButton 
					component="a"
					href={`mailto:${props.email}`} 
					target="_blank"
				>
					<ListItemIcon>
						<EmailIcon />
					</ListItemIcon>
					<ListItemText 
						primary="Email"
						secondary={props.email}
					/>
				</ListItemButton>
			</Show>
			<Show when={props?.phone}>
				<ListItemButton
					component="a"
					href={`tel:${props.phone}`}
				>
					<ListItemIcon>
						<PhoneIcon />
					</ListItemIcon>
					<ListItemText 
						primary="Phone"
						secondary={props.phone}
					/>
				</ListItemButton>
			</Show>
			<Show when={props?.facebook}>
				<ListItemButton
					component="a"
					href={props.facebook}
				>
					<ListItemIcon>
						<SvgIcon>
							<FacebookSvg />
						</SvgIcon>
					</ListItemIcon>
					<ListItemText 
						primary="Facebook"
						secondary={props.facebook}
					/>
				</ListItemButton>
			</Show>
			<Show when={props?.instagram}>
				<ListItemButton
					component="a"
					href={props.instagram}
				>
					<ListItemIcon>
						<SvgIcon>
							<InstagramSvg />
						</SvgIcon>
					</ListItemIcon>
					<ListItemText 
						primary="Instagram"
						secondary={props.instagram}
					/>
				</ListItemButton>
			</Show>
		</List>
	);
}

// src/components/ContactList.svelte
<script lang="ts">
	import ListItem from "./ListItem.svelte";
	import FacebookIcon from "../resources/icons/facebook.svelte";
	import InstagramIcon from "../resources/icons/instagram.svelte";

	export let facebook: string = "";
	export let instagram: string = "";
	export let phone: string = "";
	export let email: string = "";
	export let website: string = "";
</script>

<div>
	<h4 class="text-sm opacity-50">Contact</h4>

	{#if website}
		<a href={website} target="_blank" rel="noopener noreferrer">
			<ListItem primary="Website" secondary={website} icon="web" button />
		</a>
	{/if}

	{#if email}
		<a href={`mailto:${email}`} target="_blank" rel="noopener noreferrer">
			<ListItem primary="Email" secondary={email} icon="mail" button />
		</a>
	{/if}

	{#if phone}
		<a href={`tel:${phone}`} target="_blank" rel="noopener noreferrer">
			<ListItem primary="Telefon" secondary={phone} icon="phone" button />
		</a>
	{/if}

	{#if facebook}
		<a href={facebook} target="_blank" rel="noopener noreferrer">
			<ListItem primary="Facebook" secondary={facebook} iconElement={FacebookIcon} button />
		</a>
	{/if}

	{#if instagram}
		<a href={instagram} target="_blank" rel="noopener noreferrer">
			<ListItem primary="Instagram" secondary={instagram} iconElement={InstagramIcon} button />
		</a>
	{/if}
</div>
